/**
 * generated by Xtext 2.15.0
 */
package compilation.ui;

import compilation.ui.AbstractWhileLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WhileLanguageUiModule extends AbstractWhileLanguageUiModule {
  public WhileLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
