/**
 * generated by Xtext 2.15.0
 */
package compilation.whileLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Commands</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link compilation.whileLanguage.Commands#getCommand <em>Command</em>}</li>
 *   <li>{@link compilation.whileLanguage.Commands#getCommands <em>Commands</em>}</li>
 * </ul>
 * </p>
 *
 * @see compilation.whileLanguage.WhileLanguagePackage#getCommands()
 * @model
 * @generated
 */
public interface Commands extends EObject
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Command</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' containment reference.
   * @see #setCommand(Command)
   * @see compilation.whileLanguage.WhileLanguagePackage#getCommands_Command()
   * @model containment="true"
   * @generated
   */
  Command getCommand();

  /**
   * Sets the value of the '{@link compilation.whileLanguage.Commands#getCommand <em>Command</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' containment reference.
   * @see #getCommand()
   * @generated
   */
  void setCommand(Command value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference list.
   * The list contents are of type {@link compilation.whileLanguage.Command}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference list.
   * @see compilation.whileLanguage.WhileLanguagePackage#getCommands_Commands()
   * @model containment="true"
   * @generated
   */
  EList<Command> getCommands();

} // Commands
