/**
 * generated by Xtext 2.15.0
 */
package compilation.whileLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Lexpr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link compilation.whileLanguage.Lexpr#getExprs <em>Exprs</em>}</li>
 * </ul>
 * </p>
 *
 * @see compilation.whileLanguage.WhileLanguagePackage#getLexpr()
 * @model
 * @generated
 */
public interface Lexpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Exprs</b></em>' containment reference list.
   * The list contents are of type {@link compilation.whileLanguage.Expr}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exprs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exprs</em>' containment reference list.
   * @see compilation.whileLanguage.WhileLanguagePackage#getLexpr_Exprs()
   * @model containment="true"
   * @generated
   */
  EList<Expr> getExprs();

} // Lexpr
