/**
 * generated by Xtext 2.15.0
 */
package compilation.whileLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see compilation.whileLanguage.WhileLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface WhileLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "whileLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.WhileLanguage.compilation";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "whileLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WhileLanguagePackage eINSTANCE = compilation.whileLanguage.impl.WhileLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.ProgramImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Functions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__FUNCTIONS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.FunctionImpl <em>Function</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.FunctionImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getFunction()
   * @generated
   */
  int FUNCTION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Definition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION__DEFINITION = 1;

  /**
   * The number of structural features of the '<em>Function</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FUNCTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.DefinitionImpl <em>Definition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.DefinitionImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getDefinition()
   * @generated
   */
  int DEFINITION = 2;

  /**
   * The feature id for the '<em><b>Read</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__READ = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__COMMANDS = 1;

  /**
   * The feature id for the '<em><b>Write</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION__WRITE = 2;

  /**
   * The number of structural features of the '<em>Definition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEFINITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.ReadImpl <em>Read</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.ReadImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getRead()
   * @generated
   */
  int READ = 3;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ__VARIABLE = 0;

  /**
   * The number of structural features of the '<em>Read</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int READ_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.WriteImpl <em>Write</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.WriteImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getWrite()
   * @generated
   */
  int WRITE = 4;

  /**
   * The feature id for the '<em><b>Variable</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE__VARIABLE = 0;

  /**
   * The number of structural features of the '<em>Write</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WRITE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.AffectationImpl <em>Affectation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.AffectationImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getAffectation()
   * @generated
   */
  int AFFECTATION = 5;

  /**
   * The feature id for the '<em><b>Affectations</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__AFFECTATIONS = 0;

  /**
   * The feature id for the '<em><b>Valeurs</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION__VALEURS = 1;

  /**
   * The number of structural features of the '<em>Affectation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFFECTATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.NopImpl <em>Nop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.NopImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getNop()
   * @generated
   */
  int NOP = 6;

  /**
   * The feature id for the '<em><b>Nop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP__NOP = 0;

  /**
   * The number of structural features of the '<em>Nop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.CommandsImpl <em>Commands</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.CommandsImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getCommands()
   * @generated
   */
  int COMMANDS = 7;

  /**
   * The feature id for the '<em><b>Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDS__COMMAND = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDS__COMMANDS = 1;

  /**
   * The number of structural features of the '<em>Commands</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMANDS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.CommandImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 8;

  /**
   * The feature id for the '<em><b>Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__COMMAND = 0;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.ForeachImpl <em>Foreach</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.ForeachImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getForeach()
   * @generated
   */
  int FOREACH = 9;

  /**
   * The feature id for the '<em><b>Expr1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOREACH__EXPR1 = 0;

  /**
   * The feature id for the '<em><b>Expr2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOREACH__EXPR2 = 1;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOREACH__COMMANDS = 2;

  /**
   * The number of structural features of the '<em>Foreach</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOREACH_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.IfImpl <em>If</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.IfImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getIf()
   * @generated
   */
  int IF = 10;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__EXPR = 0;

  /**
   * The feature id for the '<em><b>Commands1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__COMMANDS1 = 1;

  /**
   * The feature id for the '<em><b>Commands2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF__COMMANDS2 = 2;

  /**
   * The number of structural features of the '<em>If</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.ForImpl <em>For</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.ForImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getFor()
   * @generated
   */
  int FOR = 11;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__EXPR = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR__COMMANDS = 1;

  /**
   * The number of structural features of the '<em>For</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.WhileImpl <em>While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.WhileImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getWhile()
   * @generated
   */
  int WHILE = 12;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__EXPR = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE__COMMANDS = 1;

  /**
   * The number of structural features of the '<em>While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.ExprImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getExpr()
   * @generated
   */
  int EXPR = 13;

  /**
   * The feature id for the '<em><b>Exprsimple</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR__EXPRSIMPLE = 0;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.ExprSimpleImpl <em>Expr Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.ExprSimpleImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getExprSimple()
   * @generated
   */
  int EXPR_SIMPLE = 14;

  /**
   * The feature id for the '<em><b>Valeur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__VALEUR = 0;

  /**
   * The feature id for the '<em><b>Ope</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__OPE = 1;

  /**
   * The feature id for the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__LEXPR = 2;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__EXPR = 3;

  /**
   * The feature id for the '<em><b>Call</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__CALL = 4;

  /**
   * The feature id for the '<em><b>Ex1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__EX1 = 5;

  /**
   * The feature id for the '<em><b>Ex2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE__EX2 = 6;

  /**
   * The number of structural features of the '<em>Expr Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_SIMPLE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link compilation.whileLanguage.impl.LexprImpl <em>Lexpr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see compilation.whileLanguage.impl.LexprImpl
   * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getLexpr()
   * @generated
   */
  int LEXPR = 15;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEXPR__EXPR = 0;

  /**
   * The feature id for the '<em><b>Lexpr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEXPR__LEXPR = 1;

  /**
   * The number of structural features of the '<em>Lexpr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEXPR_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see compilation.whileLanguage.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link compilation.whileLanguage.Program#getFunctions <em>Functions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Functions</em>'.
   * @see compilation.whileLanguage.Program#getFunctions()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Functions();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Function <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Function</em>'.
   * @see compilation.whileLanguage.Function
   * @generated
   */
  EClass getFunction();

  /**
   * Returns the meta object for the attribute '{@link compilation.whileLanguage.Function#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see compilation.whileLanguage.Function#getName()
   * @see #getFunction()
   * @generated
   */
  EAttribute getFunction_Name();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Function#getDefinition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Definition</em>'.
   * @see compilation.whileLanguage.Function#getDefinition()
   * @see #getFunction()
   * @generated
   */
  EReference getFunction_Definition();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Definition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Definition</em>'.
   * @see compilation.whileLanguage.Definition
   * @generated
   */
  EClass getDefinition();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Definition#getRead <em>Read</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Read</em>'.
   * @see compilation.whileLanguage.Definition#getRead()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Read();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Definition#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commands</em>'.
   * @see compilation.whileLanguage.Definition#getCommands()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Commands();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Definition#getWrite <em>Write</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Write</em>'.
   * @see compilation.whileLanguage.Definition#getWrite()
   * @see #getDefinition()
   * @generated
   */
  EReference getDefinition_Write();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Read <em>Read</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Read</em>'.
   * @see compilation.whileLanguage.Read
   * @generated
   */
  EClass getRead();

  /**
   * Returns the meta object for the attribute list '{@link compilation.whileLanguage.Read#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Variable</em>'.
   * @see compilation.whileLanguage.Read#getVariable()
   * @see #getRead()
   * @generated
   */
  EAttribute getRead_Variable();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Write <em>Write</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Write</em>'.
   * @see compilation.whileLanguage.Write
   * @generated
   */
  EClass getWrite();

  /**
   * Returns the meta object for the attribute list '{@link compilation.whileLanguage.Write#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Variable</em>'.
   * @see compilation.whileLanguage.Write#getVariable()
   * @see #getWrite()
   * @generated
   */
  EAttribute getWrite_Variable();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Affectation <em>Affectation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Affectation</em>'.
   * @see compilation.whileLanguage.Affectation
   * @generated
   */
  EClass getAffectation();

  /**
   * Returns the meta object for the attribute list '{@link compilation.whileLanguage.Affectation#getAffectations <em>Affectations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Affectations</em>'.
   * @see compilation.whileLanguage.Affectation#getAffectations()
   * @see #getAffectation()
   * @generated
   */
  EAttribute getAffectation_Affectations();

  /**
   * Returns the meta object for the containment reference list '{@link compilation.whileLanguage.Affectation#getValeurs <em>Valeurs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Valeurs</em>'.
   * @see compilation.whileLanguage.Affectation#getValeurs()
   * @see #getAffectation()
   * @generated
   */
  EReference getAffectation_Valeurs();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Nop <em>Nop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Nop</em>'.
   * @see compilation.whileLanguage.Nop
   * @generated
   */
  EClass getNop();

  /**
   * Returns the meta object for the attribute '{@link compilation.whileLanguage.Nop#getNop <em>Nop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nop</em>'.
   * @see compilation.whileLanguage.Nop#getNop()
   * @see #getNop()
   * @generated
   */
  EAttribute getNop_Nop();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Commands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Commands</em>'.
   * @see compilation.whileLanguage.Commands
   * @generated
   */
  EClass getCommands();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Commands#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Command</em>'.
   * @see compilation.whileLanguage.Commands#getCommand()
   * @see #getCommands()
   * @generated
   */
  EReference getCommands_Command();

  /**
   * Returns the meta object for the containment reference list '{@link compilation.whileLanguage.Commands#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see compilation.whileLanguage.Commands#getCommands()
   * @see #getCommands()
   * @generated
   */
  EReference getCommands_Commands();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see compilation.whileLanguage.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Command#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Command</em>'.
   * @see compilation.whileLanguage.Command#getCommand()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Command();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Foreach <em>Foreach</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Foreach</em>'.
   * @see compilation.whileLanguage.Foreach
   * @generated
   */
  EClass getForeach();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Foreach#getExpr1 <em>Expr1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr1</em>'.
   * @see compilation.whileLanguage.Foreach#getExpr1()
   * @see #getForeach()
   * @generated
   */
  EReference getForeach_Expr1();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Foreach#getExpr2 <em>Expr2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr2</em>'.
   * @see compilation.whileLanguage.Foreach#getExpr2()
   * @see #getForeach()
   * @generated
   */
  EReference getForeach_Expr2();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Foreach#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commands</em>'.
   * @see compilation.whileLanguage.Foreach#getCommands()
   * @see #getForeach()
   * @generated
   */
  EReference getForeach_Commands();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.If <em>If</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If</em>'.
   * @see compilation.whileLanguage.If
   * @generated
   */
  EClass getIf();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.If#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see compilation.whileLanguage.If#getExpr()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Expr();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.If#getCommands1 <em>Commands1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commands1</em>'.
   * @see compilation.whileLanguage.If#getCommands1()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Commands1();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.If#getCommands2 <em>Commands2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commands2</em>'.
   * @see compilation.whileLanguage.If#getCommands2()
   * @see #getIf()
   * @generated
   */
  EReference getIf_Commands2();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.For <em>For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>For</em>'.
   * @see compilation.whileLanguage.For
   * @generated
   */
  EClass getFor();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.For#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see compilation.whileLanguage.For#getExpr()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Expr();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.For#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commands</em>'.
   * @see compilation.whileLanguage.For#getCommands()
   * @see #getFor()
   * @generated
   */
  EReference getFor_Commands();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.While <em>While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While</em>'.
   * @see compilation.whileLanguage.While
   * @generated
   */
  EClass getWhile();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.While#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see compilation.whileLanguage.While#getExpr()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Expr();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.While#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Commands</em>'.
   * @see compilation.whileLanguage.While#getCommands()
   * @see #getWhile()
   * @generated
   */
  EReference getWhile_Commands();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see compilation.whileLanguage.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Expr#getExprsimple <em>Exprsimple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exprsimple</em>'.
   * @see compilation.whileLanguage.Expr#getExprsimple()
   * @see #getExpr()
   * @generated
   */
  EReference getExpr_Exprsimple();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.ExprSimple <em>Expr Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr Simple</em>'.
   * @see compilation.whileLanguage.ExprSimple
   * @generated
   */
  EClass getExprSimple();

  /**
   * Returns the meta object for the attribute '{@link compilation.whileLanguage.ExprSimple#getValeur <em>Valeur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Valeur</em>'.
   * @see compilation.whileLanguage.ExprSimple#getValeur()
   * @see #getExprSimple()
   * @generated
   */
  EAttribute getExprSimple_Valeur();

  /**
   * Returns the meta object for the attribute '{@link compilation.whileLanguage.ExprSimple#getOpe <em>Ope</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ope</em>'.
   * @see compilation.whileLanguage.ExprSimple#getOpe()
   * @see #getExprSimple()
   * @generated
   */
  EAttribute getExprSimple_Ope();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.ExprSimple#getLexpr <em>Lexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lexpr</em>'.
   * @see compilation.whileLanguage.ExprSimple#getLexpr()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_Lexpr();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.ExprSimple#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see compilation.whileLanguage.ExprSimple#getExpr()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_Expr();

  /**
   * Returns the meta object for the attribute '{@link compilation.whileLanguage.ExprSimple#getCall <em>Call</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Call</em>'.
   * @see compilation.whileLanguage.ExprSimple#getCall()
   * @see #getExprSimple()
   * @generated
   */
  EAttribute getExprSimple_Call();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.ExprSimple#getEx1 <em>Ex1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ex1</em>'.
   * @see compilation.whileLanguage.ExprSimple#getEx1()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_Ex1();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.ExprSimple#getEx2 <em>Ex2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ex2</em>'.
   * @see compilation.whileLanguage.ExprSimple#getEx2()
   * @see #getExprSimple()
   * @generated
   */
  EReference getExprSimple_Ex2();

  /**
   * Returns the meta object for class '{@link compilation.whileLanguage.Lexpr <em>Lexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lexpr</em>'.
   * @see compilation.whileLanguage.Lexpr
   * @generated
   */
  EClass getLexpr();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Lexpr#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see compilation.whileLanguage.Lexpr#getExpr()
   * @see #getLexpr()
   * @generated
   */
  EReference getLexpr_Expr();

  /**
   * Returns the meta object for the containment reference '{@link compilation.whileLanguage.Lexpr#getLexpr <em>Lexpr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lexpr</em>'.
   * @see compilation.whileLanguage.Lexpr#getLexpr()
   * @see #getLexpr()
   * @generated
   */
  EReference getLexpr_Lexpr();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WhileLanguageFactory getWhileLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.ProgramImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Functions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__FUNCTIONS = eINSTANCE.getProgram_Functions();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.FunctionImpl <em>Function</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.FunctionImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getFunction()
     * @generated
     */
    EClass FUNCTION = eINSTANCE.getFunction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FUNCTION__NAME = eINSTANCE.getFunction_Name();

    /**
     * The meta object literal for the '<em><b>Definition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FUNCTION__DEFINITION = eINSTANCE.getFunction_Definition();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.DefinitionImpl <em>Definition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.DefinitionImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getDefinition()
     * @generated
     */
    EClass DEFINITION = eINSTANCE.getDefinition();

    /**
     * The meta object literal for the '<em><b>Read</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__READ = eINSTANCE.getDefinition_Read();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__COMMANDS = eINSTANCE.getDefinition_Commands();

    /**
     * The meta object literal for the '<em><b>Write</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEFINITION__WRITE = eINSTANCE.getDefinition_Write();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.ReadImpl <em>Read</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.ReadImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getRead()
     * @generated
     */
    EClass READ = eINSTANCE.getRead();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute READ__VARIABLE = eINSTANCE.getRead_Variable();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.WriteImpl <em>Write</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.WriteImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getWrite()
     * @generated
     */
    EClass WRITE = eINSTANCE.getWrite();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WRITE__VARIABLE = eINSTANCE.getWrite_Variable();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.AffectationImpl <em>Affectation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.AffectationImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getAffectation()
     * @generated
     */
    EClass AFFECTATION = eINSTANCE.getAffectation();

    /**
     * The meta object literal for the '<em><b>Affectations</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AFFECTATION__AFFECTATIONS = eINSTANCE.getAffectation_Affectations();

    /**
     * The meta object literal for the '<em><b>Valeurs</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFFECTATION__VALEURS = eINSTANCE.getAffectation_Valeurs();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.NopImpl <em>Nop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.NopImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getNop()
     * @generated
     */
    EClass NOP = eINSTANCE.getNop();

    /**
     * The meta object literal for the '<em><b>Nop</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOP__NOP = eINSTANCE.getNop_Nop();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.CommandsImpl <em>Commands</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.CommandsImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getCommands()
     * @generated
     */
    EClass COMMANDS = eINSTANCE.getCommands();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMANDS__COMMAND = eINSTANCE.getCommands_Command();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMANDS__COMMANDS = eINSTANCE.getCommands_Commands();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.CommandImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__COMMAND = eINSTANCE.getCommand_Command();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.ForeachImpl <em>Foreach</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.ForeachImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getForeach()
     * @generated
     */
    EClass FOREACH = eINSTANCE.getForeach();

    /**
     * The meta object literal for the '<em><b>Expr1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOREACH__EXPR1 = eINSTANCE.getForeach_Expr1();

    /**
     * The meta object literal for the '<em><b>Expr2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOREACH__EXPR2 = eINSTANCE.getForeach_Expr2();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOREACH__COMMANDS = eINSTANCE.getForeach_Commands();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.IfImpl <em>If</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.IfImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getIf()
     * @generated
     */
    EClass IF = eINSTANCE.getIf();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__EXPR = eINSTANCE.getIf_Expr();

    /**
     * The meta object literal for the '<em><b>Commands1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__COMMANDS1 = eINSTANCE.getIf_Commands1();

    /**
     * The meta object literal for the '<em><b>Commands2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF__COMMANDS2 = eINSTANCE.getIf_Commands2();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.ForImpl <em>For</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.ForImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getFor()
     * @generated
     */
    EClass FOR = eINSTANCE.getFor();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__EXPR = eINSTANCE.getFor_Expr();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOR__COMMANDS = eINSTANCE.getFor_Commands();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.WhileImpl <em>While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.WhileImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getWhile()
     * @generated
     */
    EClass WHILE = eINSTANCE.getWhile();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__EXPR = eINSTANCE.getWhile_Expr();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE__COMMANDS = eINSTANCE.getWhile_Commands();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.ExprImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '<em><b>Exprsimple</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR__EXPRSIMPLE = eINSTANCE.getExpr_Exprsimple();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.ExprSimpleImpl <em>Expr Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.ExprSimpleImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getExprSimple()
     * @generated
     */
    EClass EXPR_SIMPLE = eINSTANCE.getExprSimple();

    /**
     * The meta object literal for the '<em><b>Valeur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_SIMPLE__VALEUR = eINSTANCE.getExprSimple_Valeur();

    /**
     * The meta object literal for the '<em><b>Ope</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_SIMPLE__OPE = eINSTANCE.getExprSimple_Ope();

    /**
     * The meta object literal for the '<em><b>Lexpr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__LEXPR = eINSTANCE.getExprSimple_Lexpr();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__EXPR = eINSTANCE.getExprSimple_Expr();

    /**
     * The meta object literal for the '<em><b>Call</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPR_SIMPLE__CALL = eINSTANCE.getExprSimple_Call();

    /**
     * The meta object literal for the '<em><b>Ex1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__EX1 = eINSTANCE.getExprSimple_Ex1();

    /**
     * The meta object literal for the '<em><b>Ex2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXPR_SIMPLE__EX2 = eINSTANCE.getExprSimple_Ex2();

    /**
     * The meta object literal for the '{@link compilation.whileLanguage.impl.LexprImpl <em>Lexpr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see compilation.whileLanguage.impl.LexprImpl
     * @see compilation.whileLanguage.impl.WhileLanguagePackageImpl#getLexpr()
     * @generated
     */
    EClass LEXPR = eINSTANCE.getLexpr();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEXPR__EXPR = eINSTANCE.getLexpr_Expr();

    /**
     * The meta object literal for the '<em><b>Lexpr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEXPR__LEXPR = eINSTANCE.getLexpr_Lexpr();

  }

} //WhileLanguagePackage
