/**
 * generated by Xtext 2.15.0
 */
package compilation.whileLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Write</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link compilation.whileLanguage.Write#getVariable <em>Variable</em>}</li>
 * </ul>
 * </p>
 *
 * @see compilation.whileLanguage.WhileLanguagePackage#getWrite()
 * @model
 * @generated
 */
public interface Write extends EObject
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Variable</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' attribute list.
   * @see compilation.whileLanguage.WhileLanguagePackage#getWrite_Variable()
   * @model unique="false"
   * @generated
   */
  EList<String> getVariable();

} // Write
