/*
 * generated by Xtext 2.15.0
 */
package compilation.ui.tests;

import com.google.inject.Injector;
import compilation.ui.internal.CompilationActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class WhileLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CompilationActivator.getInstance().getInjector("compilation.WhileLanguage");
	}

}
