/*
 * generated by Xtext 2.15.0
 */
package compilation.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWhileLanguageScopeProvider extends DelegatingScopeProvider {
}
