/*
 * generated by Xtext 2.15.0
 */
package compilation.serializer;

import com.google.inject.Inject;
import compilation.services.WhileLanguageGrammarAccess;
import compilation.whileLanguage.Affectation;
import compilation.whileLanguage.Command;
import compilation.whileLanguage.Commands;
import compilation.whileLanguage.Definition;
import compilation.whileLanguage.Expr;
import compilation.whileLanguage.ExprSimple;
import compilation.whileLanguage.For;
import compilation.whileLanguage.Foreach;
import compilation.whileLanguage.Function;
import compilation.whileLanguage.If;
import compilation.whileLanguage.Lexpr;
import compilation.whileLanguage.Nop;
import compilation.whileLanguage.Program;
import compilation.whileLanguage.Read;
import compilation.whileLanguage.While;
import compilation.whileLanguage.WhileLanguagePackage;
import compilation.whileLanguage.Write;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class WhileLanguageSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private WhileLanguageGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == WhileLanguagePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case WhileLanguagePackage.AFFECTATION:
				sequence_Affectation(context, (Affectation) semanticObject); 
				return; 
			case WhileLanguagePackage.COMMAND:
				sequence_Command(context, (Command) semanticObject); 
				return; 
			case WhileLanguagePackage.COMMANDS:
				sequence_Commands(context, (Commands) semanticObject); 
				return; 
			case WhileLanguagePackage.DEFINITION:
				sequence_Definition(context, (Definition) semanticObject); 
				return; 
			case WhileLanguagePackage.EXPR:
				sequence_Expr(context, (Expr) semanticObject); 
				return; 
			case WhileLanguagePackage.EXPR_SIMPLE:
				sequence_ExprSimple(context, (ExprSimple) semanticObject); 
				return; 
			case WhileLanguagePackage.FOR:
				sequence_For(context, (For) semanticObject); 
				return; 
			case WhileLanguagePackage.FOREACH:
				sequence_Foreach(context, (Foreach) semanticObject); 
				return; 
			case WhileLanguagePackage.FUNCTION:
				sequence_Function(context, (Function) semanticObject); 
				return; 
			case WhileLanguagePackage.IF:
				sequence_If(context, (If) semanticObject); 
				return; 
			case WhileLanguagePackage.LEXPR:
				sequence_Lexpr(context, (Lexpr) semanticObject); 
				return; 
			case WhileLanguagePackage.NOP:
				sequence_Nop(context, (Nop) semanticObject); 
				return; 
			case WhileLanguagePackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case WhileLanguagePackage.READ:
				sequence_Read(context, (Read) semanticObject); 
				return; 
			case WhileLanguagePackage.WHILE:
				sequence_While(context, (While) semanticObject); 
				return; 
			case WhileLanguagePackage.WRITE:
				sequence_Write(context, (Write) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Affectation returns Affectation
	 *
	 * Constraint:
	 *     (affectations+=VARIABLE affectations+=VARIABLE* valeurs+=Expr valeurs+=Expr*)
	 */
	protected void sequence_Affectation(ISerializationContext context, Affectation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Command returns Command
	 *
	 * Constraint:
	 *     (
	 *         command=Nop | 
	 *         command=Affectation | 
	 *         command=While | 
	 *         command=For | 
	 *         command=If | 
	 *         command=Foreach
	 *     )
	 */
	protected void sequence_Command(ISerializationContext context, Command semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Commands returns Commands
	 *
	 * Constraint:
	 *     (command=Command commands+=Command*)
	 */
	protected void sequence_Commands(ISerializationContext context, Commands semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Definition returns Definition
	 *
	 * Constraint:
	 *     (read=Read commands=Commands write=Write)
	 */
	protected void sequence_Definition(ISerializationContext context, Definition semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.DEFINITION__READ) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.DEFINITION__READ));
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.DEFINITION__COMMANDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.DEFINITION__COMMANDS));
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.DEFINITION__WRITE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.DEFINITION__WRITE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDefinitionAccess().getReadReadParserRuleCall_0_0(), semanticObject.getRead());
		feeder.accept(grammarAccess.getDefinitionAccess().getCommandsCommandsParserRuleCall_2_0(), semanticObject.getCommands());
		feeder.accept(grammarAccess.getDefinitionAccess().getWriteWriteParserRuleCall_4_0(), semanticObject.getWrite());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     ExprSimple returns ExprSimple
	 *
	 * Constraint:
	 *     (
	 *         valeur='nil' | 
	 *         valeur=VARIABLE | 
	 *         valeur=SYMBOL | 
	 *         (ope='cons' lexpr=Lexpr) | 
	 *         (ope='list' lexpr=Lexpr) | 
	 *         (ope='hd' expr=Expr) | 
	 *         (ope='tl' expr=Expr) | 
	 *         (ope='!' expr=Expr) | 
	 *         (call=SYMBOL lexpr=Lexpr) | 
	 *         (ex1=Expr (ope='and' | ope='or' | ope='=?') ex2=Expr)
	 *     )
	 */
	protected void sequence_ExprSimple(ISerializationContext context, ExprSimple semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Expr returns Expr
	 *
	 * Constraint:
	 *     exprsimple=ExprSimple
	 */
	protected void sequence_Expr(ISerializationContext context, Expr semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.EXPR__EXPRSIMPLE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.EXPR__EXPRSIMPLE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getExprAccess().getExprsimpleExprSimpleParserRuleCall_0(), semanticObject.getExprsimple());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     For returns For
	 *
	 * Constraint:
	 *     (expr=Expr commands=Commands)
	 */
	protected void sequence_For(ISerializationContext context, For semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.FOR__EXPR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.FOR__EXPR));
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.FOR__COMMANDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.FOR__COMMANDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getForAccess().getExprExprParserRuleCall_1_0(), semanticObject.getExpr());
		feeder.accept(grammarAccess.getForAccess().getCommandsCommandsParserRuleCall_3_0(), semanticObject.getCommands());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Foreach returns Foreach
	 *
	 * Constraint:
	 *     (expr1=Expr expr2=Expr commands=Commands)
	 */
	protected void sequence_Foreach(ISerializationContext context, Foreach semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.FOREACH__EXPR1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.FOREACH__EXPR1));
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.FOREACH__EXPR2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.FOREACH__EXPR2));
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.FOREACH__COMMANDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.FOREACH__COMMANDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getForeachAccess().getExpr1ExprParserRuleCall_1_0(), semanticObject.getExpr1());
		feeder.accept(grammarAccess.getForeachAccess().getExpr2ExprParserRuleCall_3_0(), semanticObject.getExpr2());
		feeder.accept(grammarAccess.getForeachAccess().getCommandsCommandsParserRuleCall_5_0(), semanticObject.getCommands());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Function returns Function
	 *
	 * Constraint:
	 *     (name=SYMBOL definition=Definition)
	 */
	protected void sequence_Function(ISerializationContext context, Function semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.FUNCTION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.FUNCTION__NAME));
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.FUNCTION__DEFINITION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.FUNCTION__DEFINITION));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFunctionAccess().getNameSYMBOLTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getFunctionAccess().getDefinitionDefinitionParserRuleCall_3_0(), semanticObject.getDefinition());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     If returns If
	 *
	 * Constraint:
	 *     (expr=Expr commands1=Commands commands2=Commands?)
	 */
	protected void sequence_If(ISerializationContext context, If semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Lexpr returns Lexpr
	 *
	 * Constraint:
	 *     (expr=Expr lexpr=Lexpr?)
	 */
	protected void sequence_Lexpr(ISerializationContext context, Lexpr semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Nop returns Nop
	 *
	 * Constraint:
	 *     nop='nop'
	 */
	protected void sequence_Nop(ISerializationContext context, Nop semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.NOP__NOP) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.NOP__NOP));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNopAccess().getNopNopKeyword_0(), semanticObject.getNop());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     functions+=Function+
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Read returns Read
	 *
	 * Constraint:
	 *     (variable+=VARIABLE variable+=VARIABLE*)
	 */
	protected void sequence_Read(ISerializationContext context, Read semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     While returns While
	 *
	 * Constraint:
	 *     (expr=Expr commands=Commands)
	 */
	protected void sequence_While(ISerializationContext context, While semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.WHILE__EXPR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.WHILE__EXPR));
			if (transientValues.isValueTransient(semanticObject, WhileLanguagePackage.Literals.WHILE__COMMANDS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, WhileLanguagePackage.Literals.WHILE__COMMANDS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getWhileAccess().getExprExprParserRuleCall_1_0(), semanticObject.getExpr());
		feeder.accept(grammarAccess.getWhileAccess().getCommandsCommandsParserRuleCall_3_0(), semanticObject.getCommands());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Write returns Write
	 *
	 * Constraint:
	 *     (variable+=VARIABLE variable+=VARIABLE*)
	 */
	protected void sequence_Write(ISerializationContext context, Write semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
