/**
 * generated by Xtext 2.15.0
 */
package compilation.ui.contentassist;

import compilation.ui.contentassist.AbstractWhileLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class WhileLanguageProposalProvider extends AbstractWhileLanguageProposalProvider {
}
