/*
 * generated by Xtext 2.15.0
 */
package compilation


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WhileLanguageStandaloneSetup extends WhileLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new WhileLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
