/**
 * generated by Xtext 2.15.0
 */
package compilation;

import compilation.AbstractWhileLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class WhileLanguageRuntimeModule extends AbstractWhileLanguageRuntimeModule {
}
