/**
 * generated by Xtext 2.15.0
 */
package compilation;

import compilation.WhileLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class WhileLanguageStandaloneSetup extends WhileLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type WhileLanguageStandaloneSetup");
  }
}
