/**
 * generated by Xtext 2.15.0
 */
package compilation.validation;

import compilation.validation.AbstractWhileLanguageValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class WhileLanguageValidator extends AbstractWhileLanguageValidator {
}
