/**
 * generated by Xtext 2.15.0
 */
package compilation.ide;

import compilation.ide.AbstractWhileLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WhileLanguageIdeModule extends AbstractWhileLanguageIdeModule {
}
