/*
 * generated by Xtext 2.15.0
 */
package compilation.ui;

import com.google.inject.Injector;
import compilation.ui.internal.CompilationActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WhileLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CompilationActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CompilationActivator activator = CompilationActivator.getInstance();
		return activator != null ? activator.getInjector(CompilationActivator.COMPILATION_WHILELANGUAGE) : null;
	}

}
