/*
 * generated by Xtext 2.15.0
 */
package compilation.parser.antlr;

import com.google.inject.Inject;
import compilation.parser.antlr.internal.InternalWhileLanguageParser;
import compilation.services.WhileLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class WhileLanguageParser extends AbstractAntlrParser {

	@Inject
	private WhileLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalWhileLanguageParser createParser(XtextTokenStream stream) {
		return new InternalWhileLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public WhileLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(WhileLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
