/**
 * generated by Xtext 2.15.0
 */
package compilation.formatting2;

import compilation.services.WhileLanguageGrammarAccess;
import compilation.whileLanguage.Function;
import compilation.whileLanguage.Program;
import java.util.Arrays;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class WhileLanguageFormatter /* implements AbstractFormatter2  */{
  /* @Inject */@Extension
  private WhileLanguageGrammarAccess _whileLanguageGrammarAccess;
  
  protected void _format(final Program program, @Extension final /* IFormattableDocument */Object document) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field functions is undefined for the type Program"
      + "\nformat cannot be resolved");
  }
  
  protected void _format(final Function function, @Extension final /* IFormattableDocument */Object document) {
    throw new Error("Unresolved compilation problems:"
      + "\nInvalid number of arguments. The method format(Object, IFormattableDocument) is not applicable for the arguments (Definition)"
      + "\nThe method format(Object, IFormattableDocument) from the type WhileLanguageFormatter refers to the missing type IFormattableDocument");
  }
  
  public void format(final Object function, final IFormattableDocument document) {
    if (function instanceof Function
         && document != null) {
      _format((Function)function, document);
      return;
    } else if (function instanceof Program
         && document != null) {
      _format((Program)function, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(function, document).toString());
    }
  }
}
